### ISSUE TITLE
Versions/tags/extension/servicepack insanity

### ISSUE THREAD

**Issue by tipdougm** [autodesk-adn/Maya-devkit#5]
You have two tags:

- 2016
- 2016.1

From the app store:
     https://apps.exchange.autodesk.com/MAYA/en/Home/Index
and searching for 'devkit' I see two downloads:

- 2016.3 
- 2016 ext2

Can you please agree that this is unnecessarily confusing?

Thanks.

**Comment by cyrillef** [comment]
Hi
the versioning number is the devkit version - you can use any of the devkit version you want for the same Maya version. The devkit version is only a incremental version which isn't necessarily binded to a  specific Maya version. For example, you can develop a plugin for Maya 2016 SP1 with the devkit 2016.0 or 2016.

**Comment by tipdougm** [comment]
Thanks for replying!

Let me echo back what I believe you are saying:
- the GitHub TAG is two fields, separated by a dot.
- "maya version" means the binary compatibility version, and is the first field.
- "devkit version" means an incremental change that is binary-compatible, and is the second field.

So, example, "2016.3" has these two numbers separated by a period. Very clear, and I'm sure you'll agree that by this clarification, you can see that anyone would assume that "2016" means ANY version of 2016 Maya.

So, when you say, "you have to use the devkit for Extension 2" I can only assume that this means that this Github hosts no such entity, since the TAG does not reflect this in what must be the only place to encode such information: the portion preceding the devkit version, to the left of the period separator.

And worse: the exchange listed "Maya ext2" -- which has no devkit incremental number on it!

When and if GitHub does host one that is ext2-compatible, it's implied that the TAG used for the FIRST checkin will be "2016 ext2.1".

In contrast, we are using the "apiVersion", which is currently "201650" for ext2, which, correct me if I'm wrong, is the only correct way to determine binary compatibility, as it is what Maya uses to reject incompatible plugins, for instance.

Could I ask you to please consider replying to the following, as I attempt to re-open this ticket with the question:

- [ ] Can you please change the Maya-version portion of the devkit GitHub TAG to use "apiVersion"? 

Thanks again Cyril.

**Comment by mike1158** [comment]
If it's not bound to a specific Maya version, then what are these doing in the devkit?

Maya-devkit-2016.1/linux/include/maya/MTypes.h:   #define MAYA_API_VERSION 201602
Maya-devkit-2016.3/linux/include/maya/MTypes.h:   #define MAYA_API_VERSION 201610
Maya-devkit-2016-ext2/linux/include/maya/MTypes.h:#define MAYA_API_VERSION 201650

It is our experience that the devkit MUST match the version of Maya we're building for, or the plugins won't load.

Further, IMHO, there should be exactly ONE place to get the devkit from.  Here.  I agree with Doug--also having a seprate, differently-named download from Autodesk is really confusing.

-Mike

**Comment by cyrillef** [comment]
The devkit version must match the Maya version, this is true - but that means:

* devkit 2015.0, 2015.1, 2015.2, ... 2015 Ext1, 2015 Ext2 can compile plug-ins for Maya 2015 all versions
* devkit 2016.0, 2016.1, 2016.3 can compile plug-ins for Maya 2016 all versions less the 2016 Extension 2 family
* devkit 2016.5 can compile plug-ins for Maya 2016 Ext2 family

I know Extension 2 is a particular case, we usually ensure binary compatibility on a major Maya version series, but for Maya 2016 Ext2, we had to break this rule and we hope not to repeat this in future.

Last but not least - while you can use the devkit 2016.3 to build a plug-in on for Maya 2016 gold (i.e. the very first version), it is backward compatible, not forward compatible. What does it means? if the devkit introduce a new API which appears in a later version of Maya, you should not use that API for an older version of Maya in your plug-in because the API entrypoint does not yet exists there.

the MAYA_API_VERSION present in the header is the 'internal' API version which is not the devkit version. I am not sure why the Maya PM management team decided to version the devkits like this, but you are right, having 2 different numbers - one for the devkit, and a second for the API can be confusing. I am not the decision maker here.

I am posting the devkit on github to help people, not to confuse people. The idea was to quick the historical versions of all devkit, in case someone needs to retieve an older vesion. But if you feel it is a problem, I can remove this github repo :( and stick to the official place where it is posted.

Maya 2016 lastest devkit - https://apps.autodesk.com/MAYA/en/Detail/Index?id=6303159649350432165&appLang=en&os=Mac 
Maya 2016 Ext2 devkit - https://apps.autodesk.com/MAYA/en/Detail/Index?id=5595681162321676385&appLang=en&os=Linux

Looking forward to your replies,
-cyrille

**Comment by mike1158** [comment]
Hey Cyrille,
      
      Thanks for the disambiguation.  I think that at least my confusion
      comes from my incorrect assumption that by putting the Maya devkit
      on github, that it would become THE place to get it--because that
      would be really cool if it were so :)  Even at its best,
      Autodesk's main website is a huge pain to navigate.
      
      I guess I was hoping that, around the time of each Maya release,
      you or someone at Autodesk would just update this repo with the
      current state of the devkit, and tag it with the same name as the
      Maya release ("2016 ext2", "2016.5", depending on who you ask). 
      This seems like a simple workflow that would meet everyone's
      needs.
      
      Cheers,
      -Mike
      
      On 05/10/2016 03:26 AM, Cyrille wrote:
    
    
      The devkit version must match the Maya version, this is true -
        but that means:
      
        devkit 2015.0, 2015.1, 2015.2, ... 2015 Ext1, 2015 Ext2 can
          compile plug-ins for Maya 2015 all versions
        devkit 2016.0, 2016.1, 2016.3 can compile plug-ins for Maya
          2016 all versions less the 2016 Extension 2 family
        devkit 2016.5 can compile plug-ins for Maya 2016 Ext2 family
      
      I know Extension 2 is a particular case, we usually ensure
        binary compatibility on a major Maya version series, but for
        Maya 2016 Ext2, we had to break this rule and we hope not to
        repeat this in future.
      Last but not least - while you can use the devkit 2016.3 to
        build a plug-in on for Maya 2016 gold (i.e. the very first
        version), it is backward compatible, not forward compatible.
        What does it means? if the devkit introduce a new API which
        appears in a later version of Maya, you should not use that API
        for an older version of Maya in your plug-in because the API
        entrypoint does not yet exists there.
      the MAYA_API_VERSION present in the header is the 'internal'
        API version which is not the devkit version. I am not sure why
        the Maya PM management team decided to version the devkits like
        this, but you are right, having 2 different numbers - one for
        the devkit, and a second for the API can be confusing. I am not
        the decision maker here.
      I am posting the devkit on github to help people, not to
        confuse people. The idea was to quick the historical versions of
        all devkit, in case someone needs to retieve an older vesion.
        But if you feel it is a problem, I can remove this github repo
        :( and stick to the official place where it is posted.
      Maya 2016 lastest devkit - https://apps.autodesk.com/MAYA/en/Detail/Index?id=6303159649350432165&appLang=en&os=Mac
        
        Maya 2016 Ext2 devkit - https://apps.autodesk.com/MAYA/en/Detail/Index?id=5595681162321676385&appLang=en&os=Linux
      Looking forward to your replies,
        -cyrille
      —
        You are receiving this because you commented.
        Reply to this email directly or view
          it on GitHub

**Comment by cyrillef** [comment]
I agree, I will maintain the repo as much I can - I am still talk to the Autodesk legal to make Github the place to go. What I am planning to do as well is to have the readme to list Maya releases with devkit and API versions. Jsut need to find a good way to make this readable and not confusing.
